### ISSUE TITLE
Regression in 1.3.0, probably due to babel upgrade? 

### ISSUE THREAD

**Issue by davidtheclark** [wavded/babel-tape-runner#5]
My tests that were passing in Travis with 1.2.0 do not pass in any version of Node except 5 with 1.3.0. I get this error (with Node 0.12 and 4):

```
> stylelint@2.0.0 tape /home/travis/build/stylelint/stylelint
> babel-tape-runner "src/**/__tests__/*.js"
/home/travis/build/stylelint/stylelint/src/__tests__/disableRanges-integration-test.js:1
(function (exports, require, module, __filename, __dirname) { import { ruleTes
                                                              ^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at loader (/home/travis/build/stylelint/stylelint/node_modules/babel-tape-runner/node_modules/babel-core/lib/api/register/node.js:136:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/travis/build/stylelint/stylelint/node_modules/babel-tape-runner/node_modules/babel-core/lib/api/register/node.js:146:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /home/travis/build/stylelint/stylelint/node_modules/babel-tape-runner/bin/babel-tape-runner:12:7
    at Array.forEach (native)
```

**Comment by wavded** [comment]
See updated readme.  You need to also include babel-core@5 as a dependency if you want to use continue using Babel 5 instead of 6.  Another alternative is to lock in version 1.2.0 of babel-tape-runner in your package.json.

**Comment by davidtheclark** [comment]
Ok. Well, I guess "breaking change" is kind of a judgment call -- but this seems like a breaking change to me, because it broke things when I upgraded.

**Comment by wavded** [comment]
Yeah I agree, in hindsight, I should have pushed a `MAJOR` semver.  Sorry about that.  Only peeps this wouldn't have broken were those who had `babel-core@5` already as a dependency.

**Comment by svenheden** [comment]
I got bitten by this as well. Really should have bumped the major.
